import Config

# ContentLoader configuration for production
# Enable content loading on startup to ensure posts are available after deployment
config :skimsafe_blogg,
  load_content_on_startup: true,
  clear_posts_on_load: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :skimsafe_blogg, SkimsafeBloggWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :skimsafe_blogg, SkimsafeBlogg.Repo,
  pool_size: 5,
  timeout: 60_000,
  ownership_timeout: 60_000,
  journal_mode: :wal
