defmodule SkimsafeBlogg.Repo.Migrations.AddPostsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :view_count, :bigint
      add :read_time_minutes, :bigint
      add :published_at, :utc_datetime
      add :published, :boolean
      add :featured, :boolean
      add :tags, {:array, :text}, default: []
      add :author_email, :text
      add :author, :text, null: false
      add :content, :text, null: false
      add :excerpt, :text
      add :slug, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:posts)
  end
end
